### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ways** [icecondor/android#9]
Hi

I think the project is lacking in documentation. I'm having trouble understanding how to use this.

I have installed the app, registered my mail, received a link, clicked it, and the app is now reporting to the website. So far all is good.

Now, how do I access or share that information?

In the app there is no way to share anything. If I click the side-menu, and my username, I'm redirected to a website which tells me "Profile is private".

If I go to the website and enter my mail, I'm redirected to https://icecondor.com/?email=my@mail.com and nothing happens.

**Comment by ways** [comment]
Ok, got a link via mail, which let me find my profile. No problem then.

**Comment by donpdonp** [comment]
Thanks for the note and sorry for the confusion. You're doing everything right. The web site access has been subtly broken for a few days. It got a temporary fix yesterday that should enable the email on the website to work. Would you try the website once more? Also check your spam folder for the email.

The android app is simply to record data and push it to the server. Accessing the data, for viewing, sharing, etc. is all done through the website.
